name: Prettier-fix
on: [pull_request, push]

permissions:
  contents: write

jobs:
  prettier-fix:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Invoke the Prettier fix
        uses: WorkOfStan/prettier-fix@main
        with:
          commit-changes: true